version: '3.8'

networks:
  pdv-network:
    driver: bridge

services:
  pdv-database:
    image: mysql:8.0
    container_name: pdv-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_do_professor
      MYSQL_DATABASE: pvd
    ports:
      - "3306:3306"
    volumes:
      - ./pdv.sql:/docker-entrypoint-initdb.d/pdv.sql
    networks:
      - pdv-network

  pdv-backend:
    build: ./server
    container_name: pdv-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=pdv-database
      - DB_USER=root
      - DB_PASSWORD=senha_do_professor
      - DB_NAME=pvd
      - DB_PORT=3306
    depends_on:
      - pdv-database
    networks:
      - pdv-network

  pdv-frontend:
    build: .
    container_name: pdv-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - pdv-backend
    networks:
      - pdv-network